### ISSUE TITLE
System halted?

### ISSUE THREAD

**Issue by littleggghost** [thanhtam-h/rpi4-xeno3#1]
Hi, @thanhtam-h 
I try to use this prebuilt kernel but the system will halt after reboot. Could you have a check at your rpi4?
Thanks in advance!

**Comment by thanhtam-h** [comment]
Did it halt immediately after reboot?
What rpi4 RAM version do you have? 4GB?
You have to follow all 4 post processing steps here:
https://github.com/thanhtam-h/rpi4-xeno3/tree/master/prebuilt#post-processing

**Comment by littleggghost** [comment]
Thanks for your kindly answer!
The reboot procedure should after 'post-processing'.
