### ISSUE TITLE
After following Your step, i got Boot black screen

### ISSUE THREAD

**Issue by AlanCruise** [thanhtam-h/rpi4-xeno3#2]
hi bro,
i used pi4,and i just do the "prebuilt" thing, then i reboot the system, and final i got a Boot black screen issue. i just wanna to know how can i fix it, and i can't locate issues, i need your help!
Thanks a lot!

Best regards

**Comment by thanhtam-h** [comment]
Did you strictly follow 4 post processing steps here https://github.com/thanhtam-h/rpi4-xeno3/tree/master/prebuilt ? Especially step 2, 3 and 4. If you didn't do those works, you may insert your microsd into a PC and edit files directly.

**Comment by AlanCruise** [comment]
yes , i do follow you step, Especially step 2, 3 and 4. but when i do the Post processing 1 , there is a error that has some .h file can't find ,and i google for it, so i think this step does not matter, i can fix it in the further.  by a way ,i found something,and i just push a issue for it, this issue like the x server or the HDMI has something error.because i am the newer to the pi,so i found you for help.
Thanks you! 
Best regards
