### ISSUE TITLE
the HDMI display cannot work

### ISSUE THREAD

**Issue by AlanCruise** [thanhtam-h/rpi4-xeno3#3]
Hi bro,
There is a situation that after following your REDEME's step,the pi4B ,using the 4.19.86-v7l-ipipe kernel, reboot system, the HDMI display does's work after the raspberry  Startup Animation，but i just can use the ssh to login the pi4B,there still is can not use "sudo startx" to let HDMI display work. I need  your help!

Thanks a lot!

Best regards

**Comment by AlanCruise** [comment]
and i see the prebuilt thing is preempt, i wonder that you make the xenomai/kernel-prepare.sh script to modify Mercury core, not the Cobalt  core?

**Comment by thanhtam-h** [comment]
You may look at the last comment in this blog, it may be your  case: [http://www.simplerobot.net/2019/12/xenomai-3-for-raspberry-pi-4.html](url)
preempt-rt is another realtime project for Linux, in that kernel I didn't build Mercury, you may try yourself if you want, it is trivial.

**Comment by AlanCruise** [comment]
Thank you a lot !,I will check the website, but i have the "China wall" question,it will take a long time.

**Comment by AlanCruise** [comment]
I follow your step again, and i have check the website. so as far,the issue is still here,and  I don't know one thing: when i use ssh login the pi4, and use the "uname -a" , it just show PREEMPT:

pi@raspberrypi:~ $ uname -r
4.19.86-v7l-ipipe
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.86-v7l-ipipe #2 SMP PREEMPT Thu Dec 12 18:17:01 KST 2019 armv7l GNU/Linux
pi@raspberrypi:~ $ dmesg | grep Xenomai
[    0.669399] [Xenomai] scheduling class idle registered.
[    0.669420] [Xenomai] scheduling class rt registered.
[    0.669643] I-pipe: head domain Xenomai registered.
[    0.676552] [Xenomai] Cobalt v3.1-rc3

**Comment by AlanCruise** [comment]
Hi, I just use the cmd " dmesg", I find the error:
[ 5497.276778] [drm:vc4_bo_create [vc4]] *ERROR* Failed to allocate from CMA:
this always show!

**Comment by AlanCruise** [comment]
Finally , I found it, it's belong to the pi4, I turn off the [pi4]'s all items in /boot/config.txt, and everthing is ok!
