### ISSUE TITLE
Reboot failure

### ISSUE THREAD

**Issue by n1ce1995** [thanhtam-h/rpi4-xeno3#4]
I run deply.sh on raspberry pi 4B, but my raspberry pi cannot reboot.

**Comment by thanhtam-h** [comment]
You have to apply post-processing work, at least from step#2 to step#4
http://www.simplerobot.net/2019/12/xenomai-3-for-raspberry-pi-4.html
In your case, insert microsd to a host PC, edit cmdline.txt and config.txt files as above guide.

**Comment by n1ce1995** [comment]
I did it according to your instrument, but my raspberry pi still cannot reboot. When starting, I got two error :"xhci_hcd can't setup:-110" and "xhci_hcd init fail,-110".

**Comment by n1ce1995** [comment]
I use another rpi 4Bm,2GB version and deploy your prebuilt. But, RPI still cannot reboot.

**Comment by thanhtam-h** [comment]
Did you connect HDMI monitor? First, you can try to disable opengl driver by comment out line "dtoverlay=vc4-fkms-v3d" in config.txt file. If still problem, send me your cmdline.txt and config.txt files.

**Comment by n1ce1995** [comment]
I tried to build kernel on Ubuntu or use your kernel package, but all failed. And I compiled the kernel on my raspberry pi and it succeeded. I guess if it is a matter of version of compiler.
