### ISSUE TITLE
pre-built kernel with xenomai CONFIG_HZ_1000 is not set.

### ISSUE THREAD

**Issue by kafan15536900** [thanhtam-h/rpi4-xeno3#5]
hi,
thank you very much for the pre-built kernel, now i can run with xenomai3 in rpi4b.
(disabled the opengl driver with "#dtoverlay=vc4-fkms-v3d" make the hdmi to work.)
when i checked the .config, i found that the .config did not set the timer frequency to 1000Hz.
```
CONFIG_HZ_100=y
# CONFIG_HZ_1000 is not set
```
i'm wondering if this is the expected setting.
thanks again.

**Comment by thanhtam-h** [comment]
That setting doesn't affect to Xenomai performance, at least with Raspberry pi.

**Comment by kafan15536900** [comment]
thanks, i got it
